# = Configuration
#
# == This is the global Alchemy configuration file
# Please override your apps settings in your config/alchemy/config.yml file.
# You can use a handy rake task to generate it.
#
#   rake alchemy:app_structure:create:config

# Alchemys Admin Area is SSL secured. You can turn it of here. NOT RECOMMENDED!
:enable_ssl: true

# The amount of time of inactivity in minutes after which the user is kicked out of his current session.
# Only active in production environment!!!
:auto_logout_time: 30

# === Redirect options
# redirect_index: You can set to redirect (an 301 permanent, for all you SEO geeks ^_^) to first child page (typically the homepage) the index/intro page if it's not visible.
# So you don't get an 404 error if the language root page is not visible.
# redirect_to_public_child: Alchemy redirects to the first public child page found, if a page is not visible.
:redirect_index: true
:redirect_to_public_child: true

# Enabling the Ferret fulltext search engine.
# Tip! For best performance and stability install a crontab that reindexes ferrets search index periodly.
# Example: cd ~/html/alchemy/current && RAILS_ENV=production rake ferret:rebuild_index
:ferret: false

# === Pagecaching
# Enable/Disable pagecaching globally.
# Hint: You can enable/disable page caching for single PageLayouts in the page_layout.yml file.
:cache_pages: true

# === Sitemap
# Alchemy renders a nice HTML (<ul><li> style) and XML (Google conform!) Sitemap for you.
# Just place a sitemap element for a page layout in your page_layouts.yml file. Alchemy does the rest.
# ==== Options:
# show_root: Show language root page in sitemap?
# show_flag: enables the Checkbox in Page#update overlay. So your customer can set the visibilit of pages in the sitemap.
:sitemap: 
  :show_root: true
  :show_flag: false

# === Picture rendering settings
# Alchemy uses Fleximage and RMagick to render images. Use {:image_size => "XXXxYYY", :crop => BOOLEAN [true]} to resize images.
# See https://github.com/Squeegy/fleximage for further infos.
# ==== Options:
# output_image_jpg_quality: If rendered as JPG this is the quality setting for it.
# preprocess_image_resize: Large images are downsized after upload to save diskspace.
# image_store_format: Masterimage storage format. Images are rendered from this master image, so a lossless format (png) is strongly recommended.
# image_output_format: Globally image output format setting.
# TIP: You can always override the output format in the options of your Essence. I.e. {:format => :gif}
:output_image_jpg_quality: 85
:preprocess_image_resize: 1000x1000
:image_store_format: png
:image_output_format: jpg

# Set available translations for your customers.
# Currently available translations are German and English.
:translations:
  - :language_code: de
    :language: Deutsch
  - :language_code: en
    :language: English

default_translation: de

# Default language for your homepgae.
default_language:
  code: de
  name: Deutsch
  page_layout: intro
  frontpage_name: Intro

# === Mailer Settings:
# 
# To send Mails via contact forms you can create your form fields here and set which fields are to be validated.
# 
# ==== Options:
# 
# fields: An Array from Hashes with fieldname as keys and type as values. Types are ActiveRecord column types (i.e. string, text, boolean, etc.).
# validate_fields: A Hash with fieldname as key and a Hash (with :message as key and a message_id as value) as value
# 
# ==== Translating validation messages:
# 
# The message_id is passed through I18n.t so you can translate it in your language yml file.
# 
# Example:
# 
#   de:  
#     alchemy:
#      contactform:
#         validations:
#           enter_name: 'Bitte geben Sie einen Namen an'
# 
:mailer:
  :page_layout_name: contact
  :forward_to_page: false
  :mail_success_page: thanks
  :fields:
    - salutation: string
    - firstname: string
    - lastname: string
    - address: string
    - zip: string
    - city: string
    - phone: string
    - email: string
    - message: text
  :validate_fields:
    :lastname:
      :message: enter_name
    :email:
      :message: enter_mail

# === User roles
# You can add own user roles. To set permissions for this roles please add an authorization_rules.rb file in your config folder.
# Further documentation for the auth system used please visit:
# https://github.com/stffn/declarative_authorization/blob/master/README.rdoc
# 
# ==== Translating Userroles
# Userroles can be translated inside your the language yml file under:
#   alchemy:
#     user_roles:
#       rolename: Name of the role
:user_roles: [registered, author, editor, admin]

# === Uploader Settings
# Allow filetypes to upload.
# Pass * to allow all kind of files.
:uploader:
  :allowed_filetypes:
    :pictures: [jpg, jpeg, gif, png, psd, pdf]
    :attachments: [*]

# === Link Target Options
# Values for the link target selectbox inside the page link overlay.
# The value gets attached as a data-link-target attribute to the link.
# 
# == Example:
# Open all links set to overlay inside an jQuery UI Dialog Window.
# 
#   jQuery(a[data-link-target="overlay"]).dialog();
:link_target_options: [blank]

# == Alchemy core plugins configuration

alchemy_plugins:

  - name: dashboard
    navigation:
      name: 'home'
      controller: admin
      action: index
      icon: home
      sub_navigation:
        - name: 'home'
          controller: admin
          action: index
    
  - name: pages
    preview_frame:
      controller: 'admin/pages'
      action: edit
      target_controller: 'admin/pages'
      target_action: preview
    navigation:
      name: 'module: pages'
      controller: 'admin/pages'
      action: index
      icon: pages
      sub_navigation:
        - name: 'module: pages'
          controller: 'admin/pages'
          action: index
        - name: 'module: layoutpages'
          controller: 'admin/pages'
          action: layoutpages
      nested:
        - controller: 'admin/pages'
          action: edit

  - name: languages
    navigation:
      name: 'module: languages'
      controller: 'admin/languages'
      action: index
      icon: languages
      sub_navigation:
        - name: 'module: languages'
          controller: 'admin/languages'
          action: index

  - name: users
    navigation:
      name: 'module: users'
      controller: 'admin/users'
      action: index
      icon: users
      sub_navigation:
        - name: 'module: users'
          controller: 'admin/users'
          action: index
        
  - name: archive
    navigation:
      controller: 'admin/pictures'
      action: index
      name: 'module: library'
      icon: library
      sub_navigation:
        - name: 'module: images'
          controller: 'admin/pictures'
          action: index
        - name: 'module: attachments'
          controller: 'admin/attachments'
          action: index
